//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeresiyeTakip
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ayarlar
    {
        public int Id { get; set; }
        public string Tema { get; set; }
        public Nullable<int> Firma { get; set; }
        public Nullable<int> Sorgu { get; set; }
        public Nullable<int> Hesap { get; set; }
        public Nullable<int> Filtre { get; set; }
    }
}
