//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeresiyeTakip.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Borc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Borc()
        {
            this.CariKart = new HashSet<CariKart>();
        }
    
        public int id { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
        public Nullable<int> saat { get; set; }
        public Nullable<decimal> cariHesap { get; set; }
        public Nullable<int> aciklama { get; set; }
        public Nullable<decimal> tutar { get; set; }
    
        public virtual Aciklama Aciklama1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CariKart> CariKart { get; set; }
    }
}
