//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeresiyeTakip.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Firma
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Firma()
        {
            this.CariKart = new HashSet<CariKart>();
        }
    
        public int id { get; set; }
        public string kod { get; set; }
        public string firmaUnvani { get; set; }
        public string telefonNo { get; set; }
        public string adres { get; set; }
        public Nullable<int> il { get; set; }
        public string vergiDairesi { get; set; }
        public string faksNo { get; set; }
        public Nullable<int> ilce { get; set; }
        public string vergiNo { get; set; }
        public Nullable<decimal> borcLimit { get; set; }
        public Nullable<int> donem { get; set; }
        public Nullable<int> paraBirimi { get; set; }
        public Nullable<int> sifreId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CariKart> CariKart { get; set; }
        public virtual iller iller { get; set; }
        public virtual ParaBirimi ParaBirimi1 { get; set; }
        public virtual Sifre Sifre { get; set; }
    }
}
